require 'fileutils'
require 'json'
require 'erb'

class QuizDataExtractor
  attr_reader :questions, :title

  def initialize
    @questions = []
    @title = ""
  end

  def extract(file_path)
    content = File.read(file_path)
    
    if content =~ /puts\s+\"\\n=== (.+?) ===\\n\"/
      @title = $1
    else
      @title = File.basename(file_path, ".rb").capitalize
    end

    if content =~ /@questions\s*=\s*\[(.*?)\]\s*end/m
      array_content = $1
      array_content.scan(/\{.*?\}/m).each do |hash_str|
        question = {}
        hash_str.scan(/(\w+):\s*(?:"(.*?)"|'(.*?)'|([^,}\n]+))/m).each do |match|
          key = match[0].to_sym
          value = match[1] || match[2] || match[3]
          value = value.gsub('\"', '"').gsub("\'", "'") if value
          question[key] = value.to_s.strip
        end
        @questions << question unless question.empty?
      end
    end
    return self
  end
end

TEMPLATE = <<~HTML
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <style>
        .question-card {
            border: 1px solid #ddd;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
        }
        .options {
            list-style: none;
            padding: 0;
        }
        .options li {
            margin: 10px 0;
        }
        .answer-section {
            display: none;
            margin-top: 15px;
            padding: 15px;
            background-color: #f0f8ff;
            border-radius: 5px;
        }
        .toggle-btn {
            margin-top: 10px;
        }
        pre {
            background-color: #f4f4f4;
            padding: 10px;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <header>
        <a href="../index.html">← Back to Index</a>
        <h1><%= title %></h1>
    </header>

    <main>
        <% questions.each_with_index do |q, i| %>
        <div class="question-card">
            <h3>Q<%= i + 1 %>. <%= q[:title] %></h3>
            
            <% if q[:requirement] && !q[:requirement].empty? %>
            <p><strong>要件:</strong><br><%= q[:requirement].gsub(/\\n/, "<br>") %></p>
            <% end %>
            
            <% if q[:code] && !q[:code].empty? %>
            <pre><code><%= q[:code].gsub(/\\n/, "\n") %></code></pre>
            <% end %>

            <p><%= q[:question] %></p>

            <ul class="options">
                <li><strong>A:</strong> <%= q[:choice_a] %></li>
                <li><strong>B:</strong> <%= q[:choice_b] %></li>
                <% if q[:choice_c] && !q[:choice_c].empty? %>
                <li><strong>C:</strong> <%= q[:choice_c] %></li>
                <% end %>
            </ul>

            <button class="toggle-btn" onclick="document.getElementById('ans-<%= i %>').style.display = 'block'">答えを見る</button>

            <div id="ans-<%= i %>" class="answer-section">
                <p><strong>正解: <%= q[:answer] %></strong></p>
                <hr>
                <p><%= q[:explanation].to_s.gsub(/\\n/, "<br>") %></p>
            </div>
        </div>
        <% end %>
    </main>

    <footer>
        <p>Generated by Gemini CLI for Polished Ruby Programming</p>
    </footer>
</body>
</html>
HTML

INDEX_TEMPLATE = <<~HTML
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polished Ruby Programming Quizzes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
</head>
<body>
    <header>
        <h1>💎 Polished Ruby Programming Quizzes</h1>
        <p>研鑽Rubyプログラミング 学習記録・復習用クイズ集</p>
    </header>

    <main>
        <h2>Chapter 1: 組み込みクラスを最大限に活用する</h2>
        <ul>
            <% quiz_files.each do |quiz| %>
            <li>
                <a href="quizzes/<%= quiz[:filename] %>"><%= quiz[:title] %></a>
            </li>
            <% end %>
        </ul>
    </main>
</body>
</html>
HTML

output_dir = "docs"
quizzes_dir = File.join(output_dir, "quizzes")
FileUtils.mkdir_p(quizzes_dir)

quiz_files_info = []

Dir.glob("problems/ch*/*.rb").sort.each do |file_path|
  next if file_path.include?("_problem")
  next unless file_path.include?("quiz")

  puts "Processing #{file_path}..."
  extractor = QuizDataExtractor.new.extract(file_path)
  
  if extractor && !extractor.questions.empty?
    filename = File.basename(file_path, ".rb") + ".html"
    
    # テンプレートに変数を渡す際に result_with_hash を使う
    erb = ERB.new(TEMPLATE)
    # Ruby 2.6系だと result_with_hash が使えない場合があるため、明示的にハッシュをバインディングする工夫
    # ここでは安全のために変数展開済みのコンテキストを作成する
    html = erb.result_with_hash(title: extractor.title, questions: extractor.questions)
    
    File.write(File.join(quizzes_dir, filename), html)
    
    quiz_files_info << { filename: filename, title: extractor.title }
  end
end

erb_index = ERB.new(INDEX_TEMPLATE)
index_html = erb_index.result_with_hash(quiz_files: quiz_files_info)
File.write(File.join(output_dir, "index.html"), index_html)

puts "Successfully generated site in docs/!"
